### ISSUE TITLE
Read Only User or Non Creator User cannot search files

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#1065]
After setting up a read only user. That user can view every resource, but when I turn to search, they can only see shared datasets.
<img width="1195" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/77e88a63-2072-4690-855c-3b09c7ddbac8">

Related to issue #866

**Comment by tcnichol** [comment]
Since I did the read only user, I can take this issue.

**Comment by tcnichol** [comment]
I changed the title of this bug to since users other than the read only user are affected.

If you search for a filename as the creator of that file, you will find it.

If you are not the creator of the file, even if you are the owner of the dataset, the file will not appear in the search results. Only datasets will show.

This seems to be due to the way files are indexed. Datasets have a field 'user_ids' but not files.

I think I can fix this by adding this new field to the elasticsearch index.
