### ISSUE TITLE
extractor status created time is hours apart from last updated

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#412]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/13950475/229504734-dd536e7e-69a7-4baf-a42a-5e4a31906f45.png">

I noticed a weird thing that probably not related to this PR. The created time vs Last Updated time is couple hours apart but in reality it's jut seconds apart.

_Originally posted by @longshuicy in https://github.com/clowder-framework/clowder2/pull/395#pullrequestreview-1368898559_

**Comment by arunapa** [comment]
@longshuicy I checked the frontend to see if there was some issue parsing the date. However, it looks like the issue is with the backend. In the listener_jobs mongo collection, the timestamps seem to be in different timezones. Based on the values, I think the issue is that the created time is in UTC while the last updated time is in CST (i.e. local time).

<img width="433" alt="Screenshot 2023-04-05 at 11 44 21 PM" src="https://user-images.githubusercontent.com/28983148/230274010-d67820b9-76ca-4996-aaf8-aadfe5e51013.png">

**Comment by longshuicy** [comment]
Good find. Thank you
