### ISSUE TITLE
fix breadcrumb

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#569]
Breadcrumb is no longer visible. Fix this.

**Comment by lmarini** [comment]
Not sure if this is related, but I removed the breadcrumb from the dataset name to make the dataset name standout more. I just now also noticed that if we go into a folder we don't see the path. I suggest we only show the breadcrumb when a user is in a folder and show it about the files table (instead of at the top above or on the same line as the dataset name).

**Comment by tcnichol** [comment]
@lmarini i realized that i put the breadcrumb back in the dataset too and not just the folder. 

I will take it out and leave it for just the folder, unless anyone thinks it looks good as is.
