### ISSUE TITLE
Include thumbnail IDs in elasticsearch index

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#683]
In order to display thumbnails on search results without needing to fetch them from Mongo one by one, we should include thumbnail IDs in the ES index. Then we can refer to it and use thumbnail as the icons for the results where available.

**Comment by tcnichol** [comment]
I have made some progress on this issue in that I am now adding an entry in elasticsearch for index.

Questions. Thumbnails do not have names and they do not have a field for downloads. I decided to use the values from the file for those elasticsearch entries, but not sure if that is a good idea especially for downloads. 

Since there is a download route for thumbnails, I will just be adding a value there, once I figure out how that works for files so we're not counting any download just from the app loading the thumbnail.
