### ISSUE TITLE
Edit metadata definitions

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#934]
Add ability to edit metadata definition.

**Comment by ddey2** [comment]
May 16 clowder dev meeting notes -
There is some inconsistency with editing metadata definition if we already have some metadata using that. The reason, is it validates the existing data on 'Add metadata' button, it errors out if it can't validate.

Possible solution:
1. Try versioning of metadata defn
2. Use id instead of name to link metadata defn to metadata
3. Always show latest metadata versions on UI.

**Comment by ddey2** [comment]
For now, I have disabled editing metadata if there is preexisting metadata. 
I have cretaed separate task for metadata versioning #1095
